# helmfile.yaml
repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # Grafana admin secret
  - name: grafana-secret
    chart: ../../charts/raw
    namespace: monitoring
    createNamespace: true
    version: 0.2.5
    values:
      - ../../values/monitoring/grafana-secret.yaml

  # kube-prometheus-stack (includes everything: Prometheus, Operator, CRDs, Node Exporter, AlertManager)
  - name: kube-prometheus-stack
    chart: prometheus-community/kube-prometheus-stack
    namespace: monitoring
    version: ~65.0.0
    values:
      - ../../values/monitoring/prometheus.yaml

  # Loki stack (after kube-prometheus-stack so CRDs exist)
  - name: loki-stack
    chart: grafana/loki-stack
    namespace: monitoring
    createNamespace: true
    version: 2.10.2
    needs:
      - kube-prometheus-stack
    values:
      - ../../values/monitoring/loki-stack.yaml

  # Grafana (deployed last)
  - name: grafana
    chart: grafana/grafana
    namespace: monitoring
    createNamespace: true
    version: ~8.9.0
    needs:
      - grafana-secret
      - kube-prometheus-stack
      - loki-stack
    values:
      - ../../values/monitoring/grafana.yaml