{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "ethereum-infrastructure.fullname" . }}-serve-nodes
  labels:
    {{- include "ethereum-infrastructure.labels" . | nindent 4 }}
spec:
  host: {{ include "ethereum-infrastructure.serveNodeName" . }}
  trafficPolicy:
    {{- toYaml .Values.istio.destinationRule.trafficPolicy | nindent 4 }}
  # Define subsets for different deployment scenarios
  subsets:
  - name: stable
    labels:
      app.kubernetes.io/component: serve-node
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 50
        http:
          http1MaxPendingRequests: 25
          maxRequestsPerConnection: 1
      loadBalancer:
        simple: LEAST_CONN
  - name: canary
    labels:
      app.kubernetes.io/component: serve-node
      deployment: canary
    trafficPolicy:
      connectionPool:
        tcp:
          maxConnections: 10
        http:
          http1MaxPendingRequests: 5
          maxRequestsPerConnection: 1
{{- end }}
