{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "ethereum-infrastructure.fullname" . }}
  labels:
    {{- include "ethereum-infrastructure.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "ethereum-infrastructure.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  # Allow ingress from specified sources
  {{- range .Values.networkPolicy.ingress }}
  - from:
    {{- toYaml .from | nindent 4 }}
    ports:
    {{- toYaml .ports | nindent 4 }}
  {{- end }}
  # Allow health checks from Kubernetes
  - from:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: TCP
      port: 8545
    - protocol: TCP
      port: 6060
  # Allow metrics scraping
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.namespaces.observability }}
    ports:
    - protocol: TCP
      port: 6060
  egress:
  # Allow DNS resolution
  - to: []
    ports:
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 53
  # Allow NTP
  - to: []
    ports:
    - protocol: UDP
      port: 123
  # Allow HTTPS for external communication
  - to: []
    ports:
    - protocol: TCP
      port: 443
  # Allow HTTP for registry communication
  - to:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.global.namespaces.registry }}
    ports:
    - protocol: TCP
      port: 5000
  # Allow P2P communication for blockchain network
  - to: []
    ports:
    - protocol: TCP
      port: 30303
    - protocol: UDP
      port: 30303
  # Allow communication between Ethereum nodes
  - to:
    - podSelector:
        matchLabels:
          {{- include "ethereum-infrastructure.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: 8545
    - protocol: TCP
      port: 8546
    - protocol: TCP
      port: 6060
{{- end }}
