# Local Development Environment Configuration
# Optimized for single-node development with minimal resource usage

global:
  environment: local
  domain: "local.ethereum.dev"
  
  # Namespace configuration
  namespaces:
    ethereum: "ethereum"
    infrastructure: "infrastructure"
    observability: "monitoring"
    registry: "registry"
    istio: "istio-system"

  # Resource configuration - minimal for local development
  resources:
    limits:
      cpu: "2"
      memory: "4Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

  # Storage configuration
  storage:
    class: "local-path"  # Use local-path-provisioner for local development
    size: "50Gi"

  # Registry configuration
  registry:
    url: "localhost:5000"
    insecure: true

# Ethereum-specific configuration
ethereum:
  # Network configuration
  network: "sepolia"  # Use testnet for local development
  
  # Client configuration
  clients:
    geth:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: "1"
          memory: "2Gi"
        requests:
          cpu: "200m"
          memory: "512Mi"
      storage:
        size: "30Gi"
    
    nethermind:
      enabled: false  # Disable additional clients in local
      replicas: 0
    
    erigon:
      enabled: false
      replicas: 0
    
    besu:
      enabled: false
      replicas: 0

  # Sync nodes configuration
  syncNodes:
    enabled: true
    count: 1
    storage:
      size: "30Gi"
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "512Mi"

  # Serve nodes configuration
  serveNodes:
    enabled: true
    replicas: 1
    autoscaling:
      enabled: false  # Disable HPA for local
      minReplicas: 1
      maxReplicas: 2
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
      requests:
        cpu: "100m"
        memory: "256Mi"

  # Snapshot jobs configuration
  snapshotJobs:
    enabled: true
    schedule: "0 6 * * *"  # Daily at 6 AM
    retention: 3  # Keep 3 snapshots
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"

# Infrastructure configuration
infrastructure:
  # Storage classes
  storageClasses:
    - name: "local-path"
      provisioner: "rancher.io/local-path"
      reclaimPolicy: "Delete"
      allowVolumeExpansion: true

  # Network policies - relaxed for local development
  networkPolicies:
    enabled: false
    
  # RBAC - minimal for local
  rbac:
    enabled: true
    restrictive: false

# Istio configuration
istio:
  enabled: true
  # Minimal Istio configuration for local development
  components:
    pilot:
      enabled: true
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
    
    ingressGateway:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
    
    egressGateway:
      enabled: false  # Not needed for local
    
    istiod:
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"

  # Gateway configuration
  gateway:
    enabled: true
    hosts:
      - "*.local.ethereum.dev"

# Observability configuration
observability:
  # Prometheus configuration
  prometheus:
    enabled: true
    retention: "7d"  # Short retention for local
    resources:
      limits:
        cpu: "200m"
        memory: "512Mi"
    storage:
      size: "5Gi"

  # Grafana configuration
  grafana:
    enabled: true
    adminPassword: "admin"  # Simple password for local
    resources:
      limits:
        cpu: "100m"
        memory: "256Mi"

  # Loki configuration
  loki:
    enabled: true
    retention: "7d"
    resources:
      limits:
        cpu: "200m"
        memory: "512Mi"
    storage:
      size: "5Gi"

  # Mimir configuration
  mimir:
    enabled: true
    retention: "7d"
    resources:
      limits:
        cpu: "200m"
        memory: "512Mi"
    storage:
      size: "5Gi"

# Local registry configuration
registry:
  enabled: true
  ui:
    enabled: true
  persistence:
    enabled: true
    size: "10Gi"
  resources:
    limits:
      cpu: "100m"
      memory: "256Mi"
