# Production Environment Configuration
# High-availability setup with full resources and security

global:
  environment: production
  domain: "ethereum.dev"
  
  # Namespace configuration
  namespaces:
    ethereum: "ethereum-production"
    infrastructure: "infrastructure-production"
    observability: "observability-production"
    registry: "registry-production"
    istio: "istio-system"

  # Resource configuration - full resources for production
  resources:
    limits:
      cpu: "8"
      memory: "16Gi"
    requests:
      cpu: "2"
      memory: "4Gi"

  # Storage configuration
  storage:
    class: "premium-ssd"
    size: "1Ti"

  # Registry configuration
  registry:
    url: "registry.ethereum.dev"
    insecure: false

# Ethereum-specific configuration
ethereum:
  # Network configuration
  network: "mainnet"  # Production uses mainnet
  
  # Client configuration - all clients enabled for diversity
  clients:
    geth:
      enabled: true
      replicas: 3
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      storage:
        size: "800Gi"
    
    nethermind:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      storage:
        size: "800Gi"
    
    erigon:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      storage:
        size: "500Gi"  # Erigon is more storage efficient
    
    besu:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: "4"
          memory: "8Gi"
        requests:
          cpu: "1"
          memory: "2Gi"
      storage:
        size: "800Gi"

  # Sync nodes configuration
  syncNodes:
    enabled: true
    count: 4  # Multiple sync nodes for HA
    storage:
      size: "800Gi"
    resources:
      limits:
        cpu: "4"
        memory: "8Gi"
      requests:
        cpu: "1"
        memory: "2Gi"
    antiAffinity:
      enabled: true
      type: "hard"

  # Serve nodes configuration
  serveNodes:
    enabled: true
    replicas: 4
    autoscaling:
      enabled: true
      minReplicas: 4
      maxReplicas: 20
      targetCPUUtilizationPercentage: 60
      targetMemoryUtilizationPercentage: 70
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"
    antiAffinity:
      enabled: true
      type: "preferred"

  # Snapshot jobs configuration
  snapshotJobs:
    enabled: true
    schedule: "0 2 * * *"  # Daily at 2 AM
    retention: 30  # Keep 30 snapshots for production
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
    backup:
      enabled: true
      location: "s3://ethereum-snapshots-backup"

# Infrastructure configuration
infrastructure:
  # Storage classes
  storageClasses:
    - name: "premium-ssd"
      provisioner: "kubernetes.io/gce-pd"
      parameters:
        type: "pd-ssd"
        replication-type: "regional-pd"
      reclaimPolicy: "Retain"
      allowVolumeExpansion: true
    
    - name: "standard-persistent"
      provisioner: "kubernetes.io/gce-pd"
      parameters:
        type: "pd-standard"
        replication-type: "regional-pd"
      reclaimPolicy: "Retain"
      allowVolumeExpansion: true

  # Network policies - strict for production
  networkPolicies:
    enabled: true
    strict: true
    
  # RBAC - strict security
  rbac:
    enabled: true
    restrictive: true
    serviceAccounts:
      limitedPrivileges: true

  # Pod Security Standards
  podSecurity:
    enabled: true
    standard: "restricted"

# Istio configuration
istio:
  enabled: true
  # Full Istio configuration for production
  components:
    pilot:
      enabled: true
      replicas: 3
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "200m"
          memory: "256Mi"
    
    ingressGateway:
      enabled: true
      replicas: 3
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "128Mi"
      antiAffinity:
        enabled: true
    
    egressGateway:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    istiod:
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"

  # Gateway configuration
  gateway:
    enabled: true
    hosts:
      - "*.ethereum.dev"
    tls:
      enabled: true
      minTLSVersion: "TLSV1_3"

  # Security policies
  security:
    peerAuthentication:
      enabled: true
      mode: "STRICT"
    authorizationPolicies:
      enabled: true

# Observability configuration
observability:
  # Prometheus configuration
  prometheus:
    enabled: true
    retention: "90d"
    replicas: 2
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "512Mi"
    storage:
      size: "200Gi"
    alerting:
      enabled: true
      deadManSwitch: true

  # Grafana configuration
  grafana:
    enabled: true
    replicas: 2
    adminPassword: "use-secret-manager"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
    persistence:
      enabled: true
      size: "20Gi"
    auth:
      oauth:
        enabled: true

  # Loki configuration
  loki:
    enabled: true
    retention: "90d"
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
    storage:
      size: "200Gi"
    compactor:
      enabled: true

  # Mimir configuration
  mimir:
    enabled: true
    retention: "1y"
    replicas: 3
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
    storage:
      size: "500Gi"
    objectStorage:
      enabled: true
      backend: "s3"

  # Alertmanager configuration
  alertmanager:
    enabled: true
    replicas: 3
    webhooks:
      slack: true
      pagerduty: true

# Registry configuration
registry:
  enabled: true
  replicas: 2
  ui:
    enabled: true
  persistence:
    enabled: true
    size: "500Gi"
  resources:
    limits:
      cpu: "500m"
      memory: "1Gi"
  security:
    tls:
      enabled: true
    auth:
      enabled: true
    scanning:
      enabled: true
  backup:
    enabled: true
    schedule: "0 3 * * *"
