# Staging Environment Configuration
# Multi-node setup for testing with moderate resources

global:
  environment: staging
  domain: "staging.ethereum.dev"
  
  # Namespace configuration
  namespaces:
    ethereum: "ethereum-staging"
    infrastructure: "infrastructure-staging"
    observability: "observability-staging"
    registry: "registry-staging"
    istio: "istio-system"

  # Resource configuration - moderate for staging
  resources:
    limits:
      cpu: "4"
      memory: "8Gi"
    requests:
      cpu: "1"
      memory: "2Gi"

  # Storage configuration
  storage:
    class: "fast-ssd"
    size: "200Gi"

  # Registry configuration
  registry:
    url: "registry.staging.ethereum.dev"
    insecure: false

# Ethereum-specific configuration
ethereum:
  # Network configuration
  network: "sepolia"  # Use testnet for staging
  
  # Client configuration - multiple clients for testing
  clients:
    geth:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      storage:
        size: "150Gi"
    
    nethermind:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      storage:
        size: "150Gi"
    
    erigon:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: "2"
          memory: "4Gi"
        requests:
          cpu: "500m"
          memory: "1Gi"
      storage:
        size: "100Gi"  # Erigon is more storage efficient
    
    besu:
      enabled: false  # Keep disabled for staging
      replicas: 0

  # Sync nodes configuration
  syncNodes:
    enabled: true
    count: 2
    storage:
      size: "150Gi"
    resources:
      limits:
        cpu: "2"
        memory: "4Gi"
      requests:
        cpu: "500m"
        memory: "1Gi"

  # Serve nodes configuration
  serveNodes:
    enabled: true
    replicas: 2
    autoscaling:
      enabled: true
      minReplicas: 2
      maxReplicas: 6
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"
      requests:
        cpu: "200m"
        memory: "512Mi"

  # Snapshot jobs configuration
  snapshotJobs:
    enabled: true
    schedule: "0 4 * * *"  # Daily at 4 AM
    retention: 7  # Keep 7 snapshots
    resources:
      limits:
        cpu: "1"
        memory: "2Gi"

# Infrastructure configuration
infrastructure:
  # Storage classes
  storageClasses:
    - name: "fast-ssd"
      provisioner: "kubernetes.io/gce-pd"
      parameters:
        type: "pd-ssd"
      reclaimPolicy: "Retain"
      allowVolumeExpansion: true
    
    - name: "standard"
      provisioner: "kubernetes.io/gce-pd"
      parameters:
        type: "pd-standard"
      reclaimPolicy: "Retain"
      allowVolumeExpansion: true

  # Network policies - enabled for staging
  networkPolicies:
    enabled: true
    
  # RBAC - moderate security
  rbac:
    enabled: true
    restrictive: true

# Istio configuration
istio:
  enabled: true
  # Full Istio configuration for staging
  components:
    pilot:
      enabled: true
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"
    
    ingressGateway:
      enabled: true
      replicas: 2
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
    
    egressGateway:
      enabled: true
      replicas: 1
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
    
    istiod:
      resources:
        limits:
          cpu: "500m"
          memory: "512Mi"

  # Gateway configuration
  gateway:
    enabled: true
    hosts:
      - "*.staging.ethereum.dev"
    tls:
      enabled: true

# Observability configuration
observability:
  # Prometheus configuration
  prometheus:
    enabled: true
    retention: "30d"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
    storage:
      size: "50Gi"
    alerting:
      enabled: true

  # Grafana configuration
  grafana:
    enabled: true
    adminPassword: "changeme-staging"
    resources:
      limits:
        cpu: "200m"
        memory: "512Mi"
    persistence:
      enabled: true
      size: "5Gi"

  # Loki configuration
  loki:
    enabled: true
    retention: "30d"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
    storage:
      size: "50Gi"

  # Mimir configuration
  mimir:
    enabled: true
    retention: "90d"
    resources:
      limits:
        cpu: "500m"
        memory: "1Gi"
    storage:
      size: "100Gi"

# Registry configuration
registry:
  enabled: true
  ui:
    enabled: true
  persistence:
    enabled: true
    size: "100Gi"
  resources:
    limits:
      cpu: "200m"
      memory: "512Mi"
  security:
    tls:
      enabled: true
    auth:
      enabled: true
