{{- if .Values.syncNodes.enabled }}
{{- range $clientName, $clientConfig := .Values.syncNodes.clients }}
{{- if $clientConfig.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum-infrastructure.syncNodeName" $clientName }}
  labels:
    {{- include "ethereum-infrastructure.syncNodeLabels" $ | nindent 4 }}
    client: {{ $clientName }}
spec:
  type: {{ $.Values.syncNodes.service.type }}
  ports:
  - name: rpc
    port: {{ $.Values.syncNodes.service.ports.rpc }}
    targetPort: rpc
    protocol: TCP
  - name: ws
    port: {{ $.Values.syncNodes.service.ports.ws }}
    targetPort: ws
    protocol: TCP
  - name: metrics
    port: {{ $.Values.syncNodes.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  selector:
    {{- include "ethereum-infrastructure.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: sync-node
    client: {{ $clientName }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ethereum-infrastructure.syncNodeName" $clientName }}-headless
  labels:
    {{- include "ethereum-infrastructure.syncNodeLabels" $ | nindent 4 }}
    client: {{ $clientName }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: rpc
    port: {{ $.Values.syncNodes.service.ports.rpc }}
    targetPort: rpc
    protocol: TCP
  - name: ws
    port: {{ $.Values.syncNodes.service.ports.ws }}
    targetPort: ws
    protocol: TCP
  - name: metrics
    port: {{ $.Values.syncNodes.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  - name: p2p
    port: 30303
    targetPort: p2p
    protocol: TCP
  - name: p2p-udp
    port: 30303
    targetPort: p2p-udp
    protocol: UDP
  selector:
    {{- include "ethereum-infrastructure.selectorLabels" $ | nindent 4 }}
    app.kubernetes.io/component: sync-node
    client: {{ $clientName }}
{{- end }}
{{- end }}
{{- end }}
