{{- if and .Values.serveNodes.enabled .Values.serveNodes.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ethereum-serve-nodes-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ethereum-infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: serve-node
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ethereum-serve-nodes
  minReplicas: {{ .Values.serveNodes.hpa.minReplicas }}
  maxReplicas: {{ .Values.serveNodes.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.serveNodes.hpa.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.serveNodes.hpa.targetMemoryUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 300
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
      - type: Percent
        value: 10
        periodSeconds: 300
{{- end }}