{{- if and .Values.snapshotJobs.enabled .Values.snapshotJobs.cleanup.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "ethereum-infrastructure.snapshotJobName" . }}-cleanup
  labels:
    {{- include "ethereum-infrastructure.snapshotJobLabels" . | nindent 4 }}
    job-type: cleanup
spec:
  schedule: {{ .Values.snapshotJobs.cleanup.schedule | quote }}
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 3600
      backoffLimit: 3
      template:
        metadata:
          labels:
            {{- include "ethereum-infrastructure.snapshotJobLabels" . | nindent 12 }}
            job-type: cleanup
        spec:
          {{- include "ethereum-infrastructure.podSecurityContext" . | nindent 10 }}
          serviceAccountName: {{ include "ethereum-infrastructure.serviceAccountName" . }}
          restartPolicy: OnFailure
          {{- with .Values.global.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          containers:
          - name: snapshot-cleaner
            image: {{ include "ethereum-infrastructure.image" .Values.snapshotJobs.cleanup.image }}
            imagePullPolicy: {{ .Values.global.imagePullPolicy }}
            {{- include "ethereum-infrastructure.securityContext" . | nindent 12 }}
            command:
            - /bin/bash
            - /scripts/cleanup-snapshots.sh
            env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ETHEREUM_NETWORK
              value: {{ .Values.ethereum.network | quote }}
            - name: SNAPSHOT_RETENTION
              value: {{ .Values.snapshotJobs.create.retention | quote }}
            - name: REGISTRY_URL
              value: {{ .Values.global.imageRegistry | quote }}
            - name: REGISTRY_REPOSITORY
              value: {{ .Values.snapshotJobs.create.registry.repository | quote }}
            volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            {{- include "ethereum-infrastructure.resources" .Values.snapshotJobs.cleanup.resources | nindent 12 }}
          volumes:
          - name: scripts
            configMap:
              name: {{ include "ethereum-infrastructure.fullname" . }}-snapshot-scripts
              defaultMode: 0755
          {{- include "ethereum-infrastructure.nodeSelector" . | nindent 10 }}
          {{- include "ethereum-infrastructure.tolerations" . | nindent 10 }}
{{- end }}
