# Grafana admin secret configuration
resources:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
    data:
      admin-user: YWRtaW4=  # base64 encoded "admin"
      admin-password: YWRtaW4xMjM=  # base64 encoded "admin123"
