# values/monitoring/grafana.yaml
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      # Prometheus from kube-prometheus-stack
      - name: Prometheus
        type: prometheus
        url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
        access: proxy
        isDefault: true
        version: 1
        editable: true
        
      # Loki
      - name: Loki
        type: loki
        url: http://loki-stack.monitoring.svc.cluster.local:3100
        access: proxy
        isDefault: false
        version: 1
        editable: true

# Add pre-loaded dashboards
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
    - name: 'kubernetes'
      orgId: 1
      folder: 'Kubernetes'
      type: file
      disableDeletion: false
      editable: true
      options:
        path: /var/lib/grafana/dashboards/kubernetes

dashboards:
  kubernetes:
    # Cluster overview  
    kubernetes-cluster:
      gnetId: 7249
      revision: 1
      datasource: Prometheus
    # Node metrics
    node-exporter:
      gnetId: 1860
      revision: 31
      datasource: Prometheus
    # Loki logs
    loki-logs:
      gnetId: 13407
      revision: 1
      datasource: Loki

# Your existing config
persistence:
  enabled: false
resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi
admin:
  existingSecret: "grafana-admin-secret"
  userKey: admin-user
  passwordKey: admin-password