{{- if and .Values.serveNodes.enabled .Values.serveNodes.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "ethereum-infrastructure.serveNodeName" . }}
  labels:
    {{- include "ethereum-infrastructure.serveNodeLabels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "ethereum-infrastructure.serveNodeName" . }}
  minReplicas: {{ .Values.serveNodes.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.serveNodes.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.serveNodes.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.serveNodes.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.serveNodes.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.serveNodes.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 2
        periodSeconds: 60
      selectPolicy: Min
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
{{- end }}
